

# Use postgres/example user/password credentials
version: '3.1'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - 'db'

  db:
    image: postgres
    restart: always
    env_file:
      - ./services/reviews/config-env/docker-env.env
    ports:
      - "5432:5432"
